# Generated by Django 4.2.6 on 2023-10-24 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_book', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('edit_info', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_book', models.CharField(max_length=255)),
                ('related_user', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
