# Generated by Django 4.2.6 on 2023-10-27 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='static/images/users/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
